# Generated by Django 4.1.7 on 2023-05-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='pre',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='nom',
            field=models.CharField(max_length=255),
        ),
    ]
