# Generated by Django 4.1.7 on 2023-05-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0008_alter_commande_client_delete_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='nom',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.CharField(default='', max_length=255),
        ),
    ]
