# Generated by Django 4.1.7 on 2023-05-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0009_alter_produit_description_alter_produit_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='slug',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
    ]
